export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    CREATE_CONTACT: 'CREATE_CONTACT',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    FORCE_UPDATE: 'FORCE_UPDATE',
    QUICK_TRANSFER: 'QUICK_TRANSFER',
    ACCOUNT_STATEMENT: 'ACCOUNT_STATEMENT',
    ROLE_DETAILS: 'ROLE_DETAILS',
    DASHBOARD: 'DASHBOARD',
    HEADER: 'HEADER',
    RESET_HEADER: 'RESET_HEADER',
    API_DETAILS: 'API_DETAILS',
};